[2025-01-10T23:25:45.435+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-10T23:25:45.441+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_processing.france_travail_data_extraction manual__2025-01-10T23:25:41.565021+00:00 [queued]>
[2025-01-10T23:25:45.444+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_processing.france_travail_data_extraction manual__2025-01-10T23:25:41.565021+00:00 [queued]>
[2025-01-10T23:25:45.444+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-10T23:25:45.453+0000] {taskinstance.py:2889} INFO - Executing <Task(DockerOperator): france_travail_data_extraction> on 2025-01-10 23:25:41.565021+00:00
[2025-01-10T23:25:45.458+0000] {standard_task_runner.py:72} INFO - Started process 59940 to run task
[2025-01-10T23:25:45.463+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_processing', 'france_travail_data_extraction', 'manual__2025-01-10T23:25:41.565021+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/job_market_dag.py', '--cfg-path', '/tmp/tmplv22ahr5']
[2025-01-10T23:25:45.464+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask france_travail_data_extraction
[2025-01-10T23:25:45.501+0000] {task_command.py:467} INFO - Running <TaskInstance: data_processing.france_travail_data_extraction manual__2025-01-10T23:25:41.565021+00:00 [running]> on host bun
[2025-01-10T23:25:45.540+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='data_processing' AIRFLOW_CTX_TASK_ID='france_travail_data_extraction' AIRFLOW_CTX_EXECUTION_DATE='2025-01-10T23:25:41.565021+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-10T23:25:41.565021+00:00'
[2025-01-10T23:25:45.541+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-10T23:25:45.541+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-10T23:25:45.541+0000] {logging_mixin.py:190} INFO - Current task name:france_travail_data_extraction state:running start_date:2025-01-10 23:25:45.442076+00:00
[2025-01-10T23:25:45.541+0000] {logging_mixin.py:190} INFO - Dag name:data_processing and current dag run status:running
[2025-01-10T23:25:45.541+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-10T23:25:45.612+0000] {docker.py:345} INFO - Starting docker container from image aurel_extract_dock:v2
[2025-01-10T23:28:02.476+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-01-10T23:28:02.482+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-10T23:28:02.486+0000] {process_utils.py:132} INFO - Sending 15 to group 59940. PIDs of all processes in the group: [59940]
[2025-01-10T23:28:02.486+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 59940
[2025-01-10T23:28:02.489+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-10T23:28:02.498+0000] {docker.py:505} INFO - Stopping docker container
[2025-01-10T23:28:12.925+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-10T23:28:12.995+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=59940, status='terminated', exitcode=0, started='23:25:45') (59940) terminated with exit code 0
